#!/usr/bin/python
import os
import sys
import hashlib
import base64

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print 'Usage ./mkpw password'
        sys.exit(-1)
    pwd = sys.argv[1]
    salt = os.urandom(8)
    hashed = base64.b64encode(hashlib.sha256(pwd + salt).digest() + salt)
    print 'New password hash:'
    print hashed
